#!/usr/bin/env php
<?php

# This is the file for executing commands in your application.

// ---------------

if(!isset($argv[1])) {
    shell_exec('php -S localhost:80');
}

if(isset($argv[1]) and is_numeric($argv[1])) {
    shell_exec('php -S localhost:'.$argv[1]);
}

if(isset($argv[1]) and $argv[1] == '-h') {
    $help_file = file('components/help');

    foreach ($help_file as $key => $value) {
        echo $value;
    }
}

?>