#!/usr/bin/env php
<?php

require_once __DIR__ . '/interpreters/args.php';

// => Server

if (!isset($argv[1])) {
    echo "\n[-] No input args\n";
}

elseif ($argv[1] == 'server') {
    start();
}

// => Controllers

elseif ($argv[1] == 'create:controller') {
    createController($argv[2]);
}