#!/usr/bin/env php
<?php

require_once __DIR__ . '/interpreters/cli/controller.cli.php';
require_once __DIR__ . '/interpreters/cli/server/args.php';


/* 
* ------------------------------------------
* ----------------------------- :: Server
* ------------------------------------------ 
*/

if ($argv[1] && $argv[1] == '-h') {
    help($argv[1]);
}

if ($argv[1] && $argv[1] == 'server') {
    start();
}

/* 
* ------------------------------------------
* ----------------------------- :: Controllers
* ------------------------------------------ 
*/


if ($argv[1] && $argv[1] == 'controller:make') {
    makeController($argv[2]);
}