#!/usr/bin/env php
<?php

require_once __DIR__ . '/build/cli.php';

@ $argv1 = $argv[1];
@ $argv2 = $argv[2];

noArgv($argv1);
start($argv1);

// ----------------

createController($argv1, $argv2);

// ----------------

createComplex($argv1);
removeComplex($argv1);
databaseComplex($argv1);
